routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route Welcome
Route::get('/', function () {
    return view('welcome');
});
// Authentication
Auth::routes();
// Routes ressources du projet 
Route::resource('categories', 'CategoryController');
Route::resource('elements', 'ElementController');
Route::resource('events', 'EventController');
// Home du projet
Route::get('/home', 'HomeController@index')->name('home');
// Barres de recherche
Route::post('/findSearch', 'HomeController@findSearch');
Route::post('/categorize', 'HomeController@categorize');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Event extends Model
{
    use Notifiable;

    /*
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title','resume','category_id'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function categorie()
    {
        return $this->belongsTo('App\Categories');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\Categories;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::latest()->paginate(5);
        $categories = Categories::all();
  
        return view('events.index',compact('events', 'categories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categories::all();
        return view('events.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $events = Event::create([
            'title' => $request->input('title'),
            'resume' => $request->input('resume'),
            'category_id' => $request->input('category_id')
        ]);
        $events->save();
        return redirect('/events')->with('success', 'Un nouvel événement vient d\'être ajouté ! ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Event::findOrFail($id);
        $categorie= Categories::all();
        return view('events.show', compact('event','categorie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::findOrFail($id);
        $categories = Categories::all();
        return view('events.edit', compact('event','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $events = Event::whereId($id)->update([
            'title' => $request->input('title'),
            'resume' => $request->input('resume'),
            'category_id' => $request->input('category_id')
            
        ]);
        // $elements->save();
        return redirect('/events')->with('success', 'L\'événement a été modifié avec succès !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = Event::findOrFail($id);
        $event->delete();

        return redirect('/events')->with('info', 'Cet événement a bien été supprimé de la liste');
    }
}

resources/views/events/categorize.blade.php
@extends('layouts.app');

@section('content')
@if ($message = Session::get('info'))
        <div class="alert alert-info">
            <p>{{ $message }}</p>
        </div>
    @endif
    @if (isset($details))
    <div class="container">
    <h2 class="text-danger">Voici la liste associée à votre recherche:</h2>
    <a class="btn btn-danger mb-3" href="{{ route('events.index') }}"> Retour</a>
    <table class="table table-bordered">
        <tr>
            <th class="text-danger">No</th>
            <th class="text-danger">Titre</th>
            <th class="text-danger">Résumé</th>
            <th class="text-danger">Catégorie</th>
            <th class="text-danger" width="280px">Action</th>
        </tr>
        @foreach ($details as $event)
        <tr>
            <td>{{ $event->id }}</td>
            <td>{{ $event->title }}</td>
            <td>{{ $event->resume }}</td>
            <td>
            @foreach ($cat as $category)
                @if($event->category_id == $category->id)
                    <span class="badge badge-danger">{{$category->name}}</span>
                @endif
            @endforeach
            </td>
            <td>
                <form action="{{ route('events.destroy',$event->id) }}" method="POST">
   
                    <a class="btn btn-danger" href="{{ route('events.show',$event->id) }}">Voir</a>
    
                    <a class="btn btn-danger" href="{{ route('events.edit',$event->id) }}">Editer</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Suppr.</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    @endif
    </div>
    @if(isset($elements))
    <div class="container">
    <h2 class="text-danger">Voici les éléments de mêmes catégories que les événements ci-dessus :</h2>
    <table class="table table-bordered">
        <tr>
            <th class="text-danger">No</th>
            <th class="text-danger">Nom</th>
            <th class="text-danger">Résumé</th>
            <th class="text-danger">Quantité</th>
            <th class="text-danger">Catégorie</th>
            <th class="text-danger" width="280px">Action</th>
        </tr>
        @foreach ($elements as $element)
        <tr>
            <td>{{ $element->id }}</td>
            <td>{{ $element->name }}</td>
            <td>{{ $element->resume }}</td>
            <td>{{ $element->quantity }}</td>
            <td>
            @foreach ($cat as $category)
                @if($element->category_id == $category->id)
                    <span class="badge badge-danger">{{$category->name}}</span>
                @endif
            @endforeach
            </td>
            <td>
                <form action="{{ route('elements.destroy',$element->id) }}" method="POST">
   
                    <a class="btn btn-danger" href="{{ route('elements.show',$element->id) }}">Voir</a>
    
                    <a class="btn btn-danger" href="{{ route('elements.edit',$element->id) }}">Editer</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Suppr.</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    @endif
</div>
@endsection

resources/views/events/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
  <div class="card-header text-danger">
    Préparer l'organisation d'un événement
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    <form method="post" action="{{ route('events.store') }}">
        <div class="form-group">
            @csrf
            <label class="text-danger" for="title">Nom de l'événement:</label>
            <input type="text" class="form-control" name="title"/>
        </div>
        <div class="form-group">
            <label class="text-danger" for="resume">Description de cet événement :</label>
            <textarea rows="5" columns="5" class="form-control" name="resume"></textarea>
        </div>
        <div class="form-group">
            <label class="text-danger" for="category_id">Catégorie de cet événement :</label>
            <select class="form-control text-danger" name="category_id">
            @foreach($categories as $category)
            <option class="text-danger" value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
            </select>
        </div>
          <button type="submit" class="btn btn-danger">Ajouter</button>
      </form>
  </div>
</div>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
  <div class="card-header text-danger">
    Modifier cet événement :
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('events.update', $event->id ) }}" >
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label class="text-danger" for="title">Nom de l'événement:</label>
              <input type="text" class="form-control" name="title" value="{{$event->title}}"/>
          </div>
          <div class="form-group">
              <label class="text-danger" for="resume">Description de cet événement:</label>
              <textarea rows="5" columns="5" class="form-control" name="resume">{{$event->resume}}</textarea>
          </div>
          <div class="form-group">
            <label class="text-danger" for="category_id">Catégorie de cet événement :</label>
            <select class="form-control" name="category_id">
            @foreach($categories as $category)
            <option class="text-danger" value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
            </select>
          </div>
          <button type="submit" class="btn btn-danger">Modifier</button>
      </form>
  </div>
</div>
@endsection

resources/views/events/index.blade.php
@extends('layouts.app')

@section('content')
@auth
    <div class="container mb-3">
        <h2 class="text-danger">Liste des événements :</h2>
        <form action="/categorize" method="post">
            @csrf 
            <div class="form-group">
                <label class="text-danger" for="category_id">Tri par catégorie :</label>
                <select class="form-control text-danger" name="category_id">
                @foreach($categories as $category)
                <option class="text-danger" value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
                </select>
                <button type="submit" class="btn btn-danger mt-2">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                        <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                    </svg>
                    Trier</button>

            </div>
        </form>
        <a class="btn btn-danger mt-1" href="{{ route('events.create') }}"><i class="fas fa-plus-circle"> Ajouter un événement</i></a>
    </div>
@endauth
<div class="container">
<div class="table-responsive text-danger">
    <table class="table table-bordered">
      <thead>
        <tr>
            <th class="text-danger" scope="col">#</th>
            <th class="text-danger" scope="col">Nom</th>
            <th class="text-danger" scope="col">Description</th>
            <th class="text-danger" scope="col">Catégorie</th>
            <th class="text-danger" scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($events as $event)
        <tr>
            <td>{{ $i++ }}</td>
            <td>{{ $event->title }}</td>
            <td>{{ Illuminate\Support\Str::limit($event->resume, 35, $end='[...]') }}</td>
            <td>
            @foreach ($categories as $cat)
                @if($event->category_id == $cat->id)
                    <span class="badge badge-danger">{{$cat->name}}</span>
                @endif
            @endforeach
            </td>
            <td>
                <form action="{{ route('events.destroy',$event->id) }}" method="POST" onsubmit="return confirm('Êtes vous certain de vouloir supprimer cet événement ? Cette action est irréversible !')">
    
                    <a class="btn btn-danger" href="{{ route('events.show',$event->id) }}">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                            <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                        </svg>
                        Voir</a>
                    @auth
                        <a class="btn btn-danger" href="{{ route('events.edit',$event->id) }}">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                            </svg>
                            Editer</a>
        
                        @csrf
                        @method('DELETE')
        
                        <button type="submit" class="btn btn-danger">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-dash-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                <path fill-rule="evenodd" d="M3.5 8a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.5-.5z"/>
                            </svg>
                            Suppr.</button>
                    @endauth
                </form>
            </td>
        </tr>
        @endforeach
      </tbody>
    </table>
</div>
</div>
{{ $events->links() }}
@endsection

resources/views/events/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="p-3 mb-2 bg-dark text-white">
            <h3>Nom de l'événement: {{$event->title}}</h3>
            <p>Description brève de cet événement : {{$event->resume}}</p>
            @foreach($categorie as $cat)
                @if ($event->category_id == $cat->id)
                  <button type="button" class="btn btn-secondary">
                    Catégorie : <span class="badge badge-danger ml-2">{{$cat->name}}</span>
                  </button>
                @endif
            @endforeach
            <hr>
            <div class="pull-right">
                <a class="btn btn-danger" href="{{ route('events.index') }}"><i class="fa fa-reply" aria-hidden="true"> Retour</i></a>
            </div>
        </div>
    </div>
</div>
@endsection