routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route Welcome
Route::get('/', function () {
    return view('welcome');
});
// Authentication
Auth::routes();
// Routes ressources du projet 
Route::resource('categories', 'CategoryController');
Route::resource('elements', 'ElementController');
Route::resource('events', 'EventController');
// Home du projet
Route::get('/home', 'HomeController@index')->name('home');
// Barres de recherche
Route::post('/findSearch', 'HomeController@findSearch');
Route::post('/categorize', 'HomeController@categorize');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Categories;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Categories::latest()->paginate(5);
  
        return view('categories.index',compact('categories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $categories = Categories::create([
            'name' => $request->input('name'),
        ]);
        $categories->save();
   
        return redirect('/categories')->with('success', 'Votre categorie vient d\'être crée ! ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categorie = Categories::findOrFail($id);
        return view('categories.show', compact('categorie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categorie = Categories::findOrFail($id);
        return view('categories.edit', compact('categorie'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categories = Categories::whereId($id)->update([
            'name' => $request->input('name'),
        ]);
        return redirect('/categories')->with('success', 'Catégorie modifiée');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categorie = Categories::findOrFail($id);
        $categorie->delete();

        return redirect('/categories')->with('info', 'Cette catégorie a été supprimée de la liste');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
  <div class="card-header text-danger">
    Créer une catégorie
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('categories.store') }}">
          <div class="form-group">
              @csrf
              <label class="text-danger" for="name">Nom de la catégorie :</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <button type="submit" class="btn btn-danger">Créer catégorie</button>
      </form>
  </div>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
@auth 

<a class="btn btn-danger" href="{{ route('categories.create') }}"><i class="fas fa-plus-circle">Ajouter une catégorie</i></a>
<h2 class="text-danger mt-4">Liste des catégories existantes: </h2>
<table class="table table-bordered mt-3">
    <tr>
        <th class="text-danger">No</th>
        <th class="text-danger">Nom</th>
        <th class="text-danger">Action</th>
    </tr>
    @foreach ($categories as $categorie)
    <tr>
        <td>{{ $categorie->id }}</td>
        <td>{{ $categorie->name }}</td>
        <td>
            <form action="{{ route('categories.destroy',$categorie->id) }}" method="POST">

                <a class="btn btn-danger" href="{{ route('categories.edit',$categorie->id) }}">Editer</a>

                @csrf
                @method('DELETE')
  
                <button type="submit" class="btn btn-danger">Suppr.</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $categories->links() !!}
@endauth
@endsection